[package]
name = "dal"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.diesel]
features = ["sqlite"]
version = "1.4.6"

[dependencies.serde]
features = ["derive"]
version = "1.0.125"
